version: "3.9"

services: 
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: webrtc_frontend
    depends_on: 
      - backend
    env_file: ./frontend/.env
    expose: 
      - "8080"
    ports: 
      - "8080:8080"
    restart: on-failure
    volumes: 
      - /frontend/node_modules
      - ./frontend:/frontend
    stdin_open: true
    tty: true
    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: webrtc_backend
    env_file: ./backend/.env
    expose: 
      - "3030"
    ports: 
      - "3030:3030"
    restart: on-failure
    volumes: 
      - /backend/node_modules
      - ./backend:/backend